workspace:
  base: /go
  path: src/github.com/lyanchih/drone-train

pipeline:
  test:
    image: golang:1.7
    commands:
    - make test
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone
    username: drone.ci
    when:
      status:
      - success
      - failure
    template: >-
      {{ repo.name }}
      {{ build.author }}
      {{ build.link }}
      {{ if success build.status }}
        build {{ build.number }} succeeded. Good job.
      {{ else }}
        build {{ build.number }} failed. Fix me please.
      {{ end }}